[0m18:27:32.472016 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000214C2A22030>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000214C14E06E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000214C170C080>]}


============================== 18:27:32.565706 | 9bed7749-ee74-45df-a1a4-3032cfaf1bb1 ==============================
[0m18:27:32.565706 [info ] [MainThread]: Running with dbt=1.9.2
[0m18:27:32.566578 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\gurez\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt init flights_dbt', 'send_anonymous_usage_stats': 'True'}
[0m18:27:32.788267 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'WindowsPath'.. Dictionary: {'dir': WindowsPath('C:/Users/gurez/.dbt')}
[0m18:27:32.801602 [info ] [MainThread]: Creating dbt configuration folder at 
[0m18:27:32.802797 [debug] [MainThread]: Starter project path: C:\MyDocuments\pipeline-ai\.venv\Lib\site-packages\dbt\include\starter_project
[0m18:27:32.836449 [info ] [MainThread]: 
Your new dbt project "flights_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m18:27:32.836449 [info ] [MainThread]: Setting up your profile.
[0m18:30:02.876524 [info ] [MainThread]: Profile flights_dbt written to C:\Users\gurez\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m18:30:02.879537 [debug] [MainThread]: Command `dbt init` succeeded at 18:30:02.879537 after 150.71 seconds
[0m18:30:02.879537 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000214C2936C90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000214C2937200>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000214BEEEE030>]}
[0m18:30:02.880538 [debug] [MainThread]: Flushing usage events
[0m18:30:03.112225 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:49:40.867985 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020682294FE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020682079700>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000206820B04A0>]}


============================== 18:49:40.871615 | 54dc0fc5-85a6-4bfb-983f-d6fa8bf1ac2c ==============================
[0m18:49:40.871615 [info ] [MainThread]: Running with dbt=1.9.2
[0m18:49:40.872612 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\gurez\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m18:49:40.873596 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\MyDocuments\pipeline-ai\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:49:40.874598 [debug] [MainThread]: Command `dbt run` failed at 18:49:40.874598 after 0.41 seconds
[0m18:49:40.874598 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002068232DDF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020682294FE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000206818C5AC0>]}
[0m18:49:40.875599 [debug] [MainThread]: Flushing usage events
[0m18:49:41.034703 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m08:29:52.162679 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028983077A70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000289833ADB20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028982FF0B00>]}


============================== 08:29:52.168922 | 7c003732-5b65-420b-af6c-61a18eb7fed6 ==============================
[0m08:29:52.168922 [info ] [MainThread]: Running with dbt=1.9.2
[0m08:29:52.168922 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\gurez\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m08:29:52.170372 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\MyDocuments\pipeline-ai\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m08:29:52.170372 [debug] [MainThread]: Command `dbt run` failed at 08:29:52.170372 after 0.38 seconds
[0m08:29:52.171414 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002898359FCB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028983077A70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028982F35340>]}
[0m08:29:52.171414 [debug] [MainThread]: Flushing usage events
[0m08:29:52.379960 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m08:33:38.613600 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000269D3CF8650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000269D6730EC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000269D6730170>]}


============================== 08:33:38.617708 | a379266c-5fb4-4e26-aec8-a65c79c4a36e ==============================
[0m08:33:38.617708 [info ] [MainThread]: Running with dbt=1.9.2
[0m08:33:38.618707 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\gurez\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt docs generate', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m08:33:38.619727 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\MyDocuments\pipeline-ai\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m08:33:38.619727 [debug] [MainThread]: Command `dbt docs generate` failed at 08:33:38.619727 after 0.31 seconds
[0m08:33:38.620654 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000269D6A26390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000269D3CF8650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000269D6524EF0>]}
[0m08:33:38.620654 [debug] [MainThread]: Flushing usage events
[0m08:33:38.787398 [debug] [MainThread]: An error was encountered while trying to flush usage events
